apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadrun
  name: loadrun-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadrun
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: loadrun
    spec:
      containers:
        - args:
            - |-
              while true; do sleep 15; grpcurl -plaintext -d '{"a": 5, "b": 3, "forward": "zk-calc-app-02"}' -H "traceparent: 00-0018317d2edc7d4cfa75b39e88c2d570-176069a07e84acaf-01" zk-calc-app-01.zk-calc-app.svc.cluster.local:80 calculator.Calculator.CallOtherAdd; done;
          command:
            - sh
            - -c
            - --
          image: chibk/grpcurl
          imagePullPolicy: Always
          name: curl
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 40Mi
