apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadrun
  name: loadrun-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadrun
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: loadrun
    spec:
      containers:
        - args:
            - |-
              while true; do sleep 15; curl -H 'traceparent: 00-eeeeeeee'$(tr -dc 'a-f0-9' < /dev/urandom | head -c24)'-'$(tr -dc 'a-f0-9' < /dev/urandom | head -c16)'-01' -w "[%{http_code}] %{url} %{time_total}s \n"  http://bookstore1.bookstore.svc.cluster.local/books/from?target=bookstore2.bookstore.svc.cluster.local -o /dev/null -s; done;
          command:
            - sh
            - -c
            - --
          image: alpine/curl
          imagePullPolicy: Always
          name: curl
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 40Mi
