apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore1
  labels:
    app: bookstore1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore1
  template:
    metadata:
      labels:
        app: bookstore1
      annotations:
        instrumentation.opentelemetry.io/inject-go: 'default/demo-instrumentation-golang'
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: '/testapp/testapp'

    spec:
      shareProcessNamespace: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
        - name: bookstore1
          image: us-west1-docker.pkg.dev/zerok-dev/test-apps-public/zk-bookstore-app:test-logs
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
#          securityContext:
#            capabilities:
#              add:
#                - SYS_PTRACE
#            privileged: true
#            runAsUser: 0
