apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore1
  labels:
    app: bookstore1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore1
  template:
    metadata:
      labels:
        app: bookstore1
      annotations:
        instrumentation.opentelemetry.io/inject-go: 'default/demo-instrumentation-golang'
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: '/testapp/testapp'
    spec:
      shareProcessNamespace: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
        - name: bookstore1
          image: us-west1-docker.pkg.dev/zerok-dev/test-apps-public/zk-bookstore-app:test-logs
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
            privileged: true
            runAsUser: 0
        - env:
            - name: OTEL_GO_AUTO_TARGET_EXE
              value: /testapp/testapp
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_LOGS_EXPORTER
              value: none
            - name: OTEL_SERVICE_NAME
              value: bookstore1
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://aws-otel-collector.aws-collector.svc.cluster.local:4317
            - name: OTEL_RESOURCE_ATTRIBUTES_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OTEL_RESOURCE_ATTRIBUTES_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: OTEL_PROPAGATORS
              value: tracecontext,baggage
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.container.name=bookstore1,k8s.deployment.name=bookstore1,k8s.namespace.name=bookstore,k8s.node.name=$(OTEL_RESOURCE_ATTRIBUTES_NODE_NAME),k8s.pod.name=$(OTEL_RESOURCE_ATTRIBUTES_POD_NAME),service.version=0.0.3-all
          image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.3.0-alpha
          imagePullPolicy: IfNotPresent
          name: opentelemetry-auto-instrumentation
          resources:
            limits:
              cpu: 500m
              memory: 32Mi
            requests:
              cpu: 50m
              memory: 32Mi
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
            privileged: true
            runAsUser: 0
