apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore2-deployment
  labels:
    app: bookstore2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore2
  template:
    metadata:
      labels:
        app: bookstore2
    spec:
      containers:
        - name: bookstore2
          image: us-west1-docker.pkg.dev/zerok-dev/golang-testapp/testapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
